export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';
